name:  Production

on: push


jobs:
  build:
    runs-on: production

    steps:
      - name: "Debug: Docker"
        run: docker info

      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Debug: System Info"
        run: |
          whoami
          groups
          hostname
          pwd

  deploy:
    name: Deploy
    runs-on: production

    env:
      DEV_HOST: ${{ secrets.DEV_HOST }}
      RABBITMQ_USERNAME: ${{ secrets.RABBITMQ_USERNAME }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
      RABBITMQ_PORT: ${{ secrets.RABBITMQ_PORT }}
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
      CONSUMING_QUEUE: ${{ secrets.CONSUMING_QUEUE }}
      EXCHANGE: ${{ secrets.EXCHANGE }}
      LOGIN_URL: ${{ secrets.LOGIN_URL }}
      QUEUE_NAME_HEARTBEAT: ${{ secrets.QUEUE_NAME_HEARTBEAT }}
      ROUTINGKEY: ${{ secrets.ROUTINGKEY }}
      ROUTINGKEY_BUSINESS: ${{ secrets.ROUTINGKEY_BUSINESS }}
      ROUTINGKEY_CONSUMPTION: ${{ secrets.ROUTINGKEY_CONSUMPTION }}
      ROUTINGKEY_USER: ${{ secrets.ROUTINGKEY_USER }}
      SALESFORCE_PASSWORD: ${{ secrets.SALESFORCE_PASSWORD }}
      SALESFORCE_SECURITY_TOKEN: ${{ secrets.SALESFORCE_SECURITY_TOKEN }}
      SALESFORCE_USERNAME: ${{ secrets.SALESFORCE_USERNAME }}

    steps:

      - name: Check Docker Compose Syntax
        run: docker compose config

      - name: Deploy
        run: |
          docker-compose down --volumes
          docker-compose up crm-app -d --build
